#!/bin/sh
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='macOS'
fi

docker_volume_flag() {
    if [[ "$platform" == 'macOS' ]]; then
        echo "-v $(greadlink -m $1):/go/src/$(basename $1)"
    else
	echo "-v $(readlink -m $1):/go/src/$(basename $1)"
    fi
}

run_in_docker_container() {
    dvf_list=$(docker_volume_flag $@)
    echo "Volume list: $dvf_list"
    docker run --rm $dvf_list nw-group/ws $(basename -a $@)
}

run_in_docker_container $@
