#!/bin/bash

EXEC=Go/main.exe
DST=/tmp/nw-group-defi1
NAME=nw-group
IMAGE=nw-group-defi1

if [ $# -eq 4 ] ; then
	if [[ "$(docker images -q $IMAGE:latest 2> /dev/null)" == "" ]]; then
		echo "No images found. Please run 'make' first!"
	else
		CONTAINER=$(docker run -it -d $IMAGE /bin/sh)
		IDATA_PATH=$1
		IUSER_PATH=$2
		IVIEW_PATH=$3
		ICHGS_PATH=$4
		
		if [[ "$(pwd)" = *"charlatans"* ]] ; then
			GIT_PATH=$(git rev-parse --show-toplevel)
			IDATA_PATH="$GIT_PATH/defis/1/la_prosperite_des_charlatans/$1"
			IUSER_PATH="$GIT_PATH/defis/1/la_prosperite_des_charlatans/$2"
			IVIEW_PATH="$GIT_PATH/defis/1/la_prosperite_des_charlatans/$3"
			ICHGS_PATH="$GIT_PATH/defis/1/la_prosperite_des_charlatans/$4"
		fi

		IDATA=$(basename $IDATA_PATH)
		IUSER=$(basename $IUSER_PATH)
		
		DIRVIEW=$(dirname $IVIEW_PATH)
		DIRICHGS=$(dirname $ICHGS_PATH)

		docker exec $CONTAINER mkdir -p $DIRVIEW && mkdir -p $DIRICHGS

		docker cp $IDATA_PATH $CONTAINER:"$DST/$IDATA"
		docker cp $IUSER_PATH $CONTAINER:"$DST/$IUSER"
		docker exec $CONTAINER \
			./$EXEC $DST/$IDATA $DST/$IUSER $IVIEW_PATH $ICHGS_PATH
		docker cp $CONTAINER:$IVIEW_PATH $IVIEW_PATH
		docker cp $CONTAINER:$ICHGS_PATH $ICHGS_PATH
		docker stop $CONTAINER
		docker rm $CONTAINER
	fi
else
	echo "usage: ./ws data.csv user.txt view0.csv changes.txt"
fi
