# Carmack docker file
# Commands:
#   sudo docker build <path> -t <tag_name>  // Create image
#   sudo docker images                      // List of images
#   sudo docker rmi <image_id>              // Remove an image
#
# Run the conatiner
#
#   sudo docker run -it <tag_name>
#

FROM ubuntu:latest
LABEL maintainer="Luxon JEAN-PIERRE <luxon.jean.pierre@gmail.com>"
WORKDIR /tmp/
COPY *.c ./
COPY *.h ./
COPY Makefile ./
RUN apt-get update && apt-get install -y make gcc
RUN make all
