TARGET=anagram

$(TARGET):
	@echo 'It is a python file, just run it using make run'

run:
	@python $(TARGET).py ../american-english english bar aeprs

measure:
	@/usr/bin/time make run

.PHONY: anagram run 
