#!/bin/sh

if [ $# -eq 4 ] ; then
	# Entrypoint
	RUN="/scableur/run.sh --docker"
	IMG="scableur-spark-img:latest"

	# Format filenames
	DATA=$1 #$(basename "$1")
	USERS=$2 #$(basename "$2")
	VIEW0=$3 #$(basename "$3")
	CHANGES=$4 #$(basename "$4")

	# Create output files
	touch $VIEW0
	touch $CHANGES
	
	# Run application (-v allows file mounting)
##TODO: test file mounting
	docker run -i -t $IMG  \
	-v "$DATA:/scableur/input/data.csv" \
	-v "$USERS:/scableur/input/users.txt" \
	-v "$VIEW0:/scableur/output/view0.csv" \
	-v "$CHANGES:/scableur/output/changes.csv" \
	sh -c "$RUN $D_VIEW0 $D_CHANGES"

else 
	echo "sh: use: ./ws <data.csv> <user.txt> <view0.csv> <changes.txt>"
fi