#!/bin/bash

EXEC=wso
DST=/usr/src/carmack
NAME=carmack
IMAGE=carmack-image-2

if [ $# -eq 4 ] ; then
	if [[ "$(docker images -q $IMAGE:latest 2> /dev/null)" == "" ]]; then
		echo "No images found. Please run 'make' first!"
	else
#		CONTAINER=$(docker ps -aqf "ancestor=carmack-image")
		
#		if [ -z "$CONTAINER" ]; then
			CONTAINER=$(docker run -it -d $IMAGE /bin/sh)
#		fi

		IDATA_PATH=$1
		IUSER_PATH=$2
		IVIEW_PATH=$3
		ICHGS_PATH=$4
		
		if [[ "$(pwd)" = *"charlatans"* ]] ; then
			GIT_PATH=$(git rev-parse --show-toplevel)
			IDATA_PATH="$GIT_PATH/defis/2/la_prosperite_des_charlatans/$1"
			IUSER_PATH="$GIT_PATH/defis/2/la_prosperite_des_charlatans/$2"
			IVIEW_PATH="$GIT_PATH/defis/2/la_prosperite_des_charlatans/$3"
			ICHGS_PATH="$GIT_PATH/defis/2/la_prosperite_des_charlatans/$4"
		fi

		IDATA=$(basename $IDATA_PATH)
		IUSER=$(basename $IUSER_PATH)
		IVIEW=$(basename $IVIEW_PATH)
		ICHGS=$(basename $ICHGS_PATH)

		docker cp $IDATA_PATH $CONTAINER:"$DST/$IDATA"
		docker cp $IUSER_PATH $CONTAINER:"$DST/$IUSER"
		docker exec $CONTAINER \
			./$EXEC $IDATA $IUSER $IVIEW $ICHGS
		docker cp $CONTAINER:"$DST/$IVIEW" $IVIEW_PATH
		docker cp $CONTAINER:"$DST/$ICHGS" $ICHGS_PATH
		docker stop $CONTAINER
		docker rm $CONTAINER
	fi
else
	echo "usage: ./ws data.csv user.txt view0.csv changes.txt"
fi
