#! /usr/bin/python3


import sys
import os

#return a sorted String
def sort_string(word):
	sorted_list = list(word.lower())
	sorted_list.sort()
	return "".join(sorted_list)

#add a sorted string into the map
def add_sorted_string(word_map,word):
	sortedString = sort_string(word)
	if sortedString not in word_map:
		word_map[sortedString] = word
	else:
		word_map[sortedString] += "," + word

mydict_map = {}
result = []

#load dictionnary
for row in open(sys.argv[1]).readlines():
	add_sorted_string(mydict_map,row.strip("\n"))

#match each word in parameters
for i in range(2,len(sys.argv)):
	sortedString = sort_string(sys.argv[i])
	if sortedString in mydict_map:
		for s_string in mydict_map[sortedString].split(","):
			result.append(s_string)

result.sort()

for r in result:
	print(r)